name: Deploy on Sanity Publish

on:
  repository_dispatch:
    types: [sanity-publish]

concurrency:
  group: sanity-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_clp1RKrYwRsMIb3Ut5z6A98Z
          VERCEL_PROJECT_ID: prj_LW23idarOQbShjBtGnM4lU2HQApj
